# Generated by Django 4.0.4 on 2022-05-06 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('mettingId', models.CharField(max_length=255)),
                ('passcode', models.CharField(max_length=255)),
                ('date', models.DateField(auto_now_add=True)),
                ('hours', models.IntegerField(default=1)),
                ('minutes', models.ImageField(default=0, upload_to='')),
                ('startTime', models.TimeField(auto_now_add=True)),
                ('endTime', models.TimeField(default=0)),
                ('content', models.TextField(null=True)),
            ],
        ),
    ]
