# Generated by Django 4.0.4 on 2022-05-06 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0002_alter_meeting_minutes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='startTime',
            field=models.TimeField(auto_now=True),
        ),
    ]
