# Generated by Django 4.0.4 on 2022-05-06 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0003_alter_meeting_date_alter_meeting_starttime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='startTime',
            field=models.TimeField(),
        ),
    ]
