# Generated by Django 4.0.4 on 2022-05-06 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0005_alter_meeting_endtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='endTime',
            field=models.TimeField(null=True),
        ),
    ]
