# Generated by Django 4.0.4 on 2022-05-06 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0006_alter_meeting_endtime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='startTime',
            new_name='time',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='endTime',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='hours',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='minutes',
        ),
        migrations.AddField(
            model_name='meeting',
            name='url',
            field=models.URLField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
