# Generated by Django 4.0.4 on 2022-05-06 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0007_rename_starttime_meeting_time_remove_meeting_endtime_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basemodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='id',
        ),
        migrations.AddField(
            model_name='meeting',
            name='messageSID',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meeting',
            name='basemodel_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='smsapp.basemodel'),
            preserve_default=False,
        ),
    ]
