# Generated by Django 4.0.4 on 2022-05-06 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0008_basemodel_remove_meeting_id_meeting_messagesid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='messageSID',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
